version: "3.7"

services: 
    web: 
        image: nginx:1.19.1
        ports: 
            - 80:80
        volumes: 
            - /var/www/docker-trial/demo5/php:/var/www/myapp
            - /var/www/docker-trial/demo5/docker/myapp.conf:/etc/nginx/conf.d/myapp.conf
        depends_on: 
            - php

    php:
        image: php:7.3.18-fpm
        volumes:
          - /var/www/docker-trial/demo5/php:/var/www/myapp
        depends_on:
          - redis
    
    redis:
        image: redis:5.0.9
        ports:
            - 6379:6379
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
    
    composer:
        image: composer:1.10.9
        command: ["composer", "install"]
        volumes:
            - /var/www/docker-trial/demo5/php:/app

volumes: 
    redis-data: