version: "3.7"

services: 
    web:
        image: nginx:1.19.1
        ports: 
            - 80:80
        volumes: 
            - /var/www/docker-trial/demo8/php:/var/www/myapp
            - /var/www/docker-trial/demo8/docker/myapp.conf:/etc/nginx/conf.d/myapp.conf
        depends_on: 
            - php
    
    php:
        image: php-xdebug-custom
        volumes: 
            - /var/www/docker-trial/demo8/php:/var/www/myapp
            - //var/www/docker-trial/demo8/docker/php.ini:/usr/local/etc/php/php.ini