version: "3.7"

services: 
    web:
        image: nginx:1.19.1
        ports: 
            - 80:80
        volumes: 
            - /var/www/docker-trial/demo3/php:/var/www/myapp
            - /var/www/docker-trial/demo3/docker/myapp.conf:/etc/nginx/conf.d/myapp.conf
        depends_on: 
            - php
            - mysql
    
    php:
        image: php:7.3.18-fpm
        volumes: 
            - /var/www/docker-trial/demo3/php:/var/www/myapp
        depends_on: 
            - mysql
    
    mysql:
        image: mysql:5.7
        restart: always
        command: "mysqld --init-file /data/application/init.sql"
        volumes: 
            - mysql-data:/var/lib/mysql
            - ./init.sql:/data/application/init.sql
        environment: 
            MYSQL_ROOT_PASSWORD: qwerty
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        depends_on:
            - mysql
volumes: 
    mysql-data: